//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CRM_DBEntities : DbContext
    {
        public CRM_DBEntities()
            : base("name=CRM_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Front_Mission> Front_Mission { get; set; }
        public virtual DbSet<Front_Vision> Front_Vision { get; set; }
        public virtual DbSet<Hotels> Hotels { get; set; }
        public virtual DbSet<Hotels_Features> Hotels_Features { get; set; }
        public virtual DbSet<Hotels_Hotel_Features> Hotels_Hotel_Features { get; set; }
        public virtual DbSet<Hotels_Hotel_Payments> Hotels_Hotel_Payments { get; set; }
        public virtual DbSet<Hotels_Hotel_Phones> Hotels_Hotel_Phones { get; set; }
        public virtual DbSet<Hotels_Hotel_Videos> Hotels_Hotel_Videos { get; set; }
        public virtual DbSet<Hotles_Hotel_Offers> Hotles_Hotel_Offers { get; set; }
        public virtual DbSet<SystemParameter_Cities> SystemParameter_Cities { get; set; }
        public virtual DbSet<SystemParameter_Countries> SystemParameter_Countries { get; set; }
        public virtual DbSet<SystemParameter_Departments> SystemParameter_Departments { get; set; }
        public virtual DbSet<SystemParameter_PaymentType> SystemParameter_PaymentType { get; set; }
        public virtual DbSet<Systemparameters_Languages> Systemparameters_Languages { get; set; }
        public virtual DbSet<Hotels_Hotel_Images> Hotels_Hotel_Images { get; set; }
        public virtual DbSet<SystemParameters_LanguageText> SystemParameters_LanguageText { get; set; }
    
        public virtual ObjectResult<procedure_productCategoryTree_Result> procedure_productCategoryTree()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<procedure_productCategoryTree_Result>("procedure_productCategoryTree");
        }
    
        public virtual ObjectResult<SP_GetAllCouriers_Result> SP_GetAllCouriers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetAllCouriers_Result>("SP_GetAllCouriers");
        }
    
        public virtual ObjectResult<SP_GetCourierDetails_Result> SP_GetCourierDetails(Nullable<System.Guid> courierID)
        {
            var courierIDParameter = courierID.HasValue ?
                new ObjectParameter("CourierID", courierID) :
                new ObjectParameter("CourierID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetCourierDetails_Result>("SP_GetCourierDetails", courierIDParameter);
        }
    
        public virtual int SP_SaveCourier(Nullable<bool> insert)
        {
            var insertParameter = insert.HasValue ?
                new ObjectParameter("Insert", insert) :
                new ObjectParameter("Insert", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SaveCourier", insertParameter);
        }
    
        public virtual int SP_SaveCustomer(Nullable<bool> insert)
        {
            var insertParameter = insert.HasValue ?
                new ObjectParameter("Insert", insert) :
                new ObjectParameter("Insert", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SaveCustomer", insertParameter);
        }
    }
}
