//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemParameters_LanguageText
    {
        public int Id { get; set; }
        public Nullable<System.Guid> SGuid { get; set; }
        public Nullable<int> LanguageKey { get; set; }
        public string LanguageName { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> Show { get; set; }
        public string Value { get; set; }
    }
}
