//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemParameter_Departments
    {
        public int Id { get; set; }
        public Nullable<System.Guid> SGuid { get; set; }
        public string DisplayValue { get; set; }
        public Nullable<int> LookupKey { get; set; }
        public Nullable<System.Guid> LookupKeyGuid { get; set; }
        public Nullable<bool> IsCurrent { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime LastModificationTime { get; set; }
        public Nullable<int> LastModifierUserId { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public Nullable<int> CreatorUserId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
        public Nullable<int> DeleterUserId { get; set; }
        public bool Show { get; set; }
    }
}
