//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMG_Portal.Content.Admin.SystemParameters {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Contact {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Contact() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GMG_Portal.Content.Admin.SystemParameters.Contact", typeof(Contact).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to address.
        /// </summary>
        public static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Count.
        /// </summary>
        public static string ApplyCount {
            get {
                return ResourceManager.GetString("ApplyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string BtnAdd {
            get {
                return ResourceManager.GetString("BtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string btnSaveLbl {
            get {
                return ResourceManager.GetString("btnSaveLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t be deleted.
        /// </summary>
        public static string CannotDeleted {
            get {
                return ResourceManager.GetString("CannotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Career Level.
        /// </summary>
        public static string CareerLevel {
            get {
                return ResourceManager.GetString("CareerLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Successfully.
        /// </summary>
        public static string DeleteSuccessMessage {
            get {
                return ResourceManager.GetString("DeleteSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Desc {
            get {
                return ResourceManager.GetString("Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DescDisplay {
            get {
                return ResourceManager.GetString("DescDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Front.
        /// </summary>
        public static string DisplayFront {
            get {
                return ResourceManager.GetString("DisplayFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string DisplayValueAddress {
            get {
                return ResourceManager.GetString("DisplayValueAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education Level.
        /// </summary>
        public static string EducationLevel {
            get {
                return ResourceManager.GetString("EducationLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name must be unique.
        /// </summary>
        public static string EnglishNameUnique {
            get {
                return ResourceManager.GetString("EnglishNameUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience.
        /// </summary>
        public static string Experience {
            get {
                return ResourceManager.GetString("Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string Facebook {
            get {
                return ResourceManager.GetString("Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        public static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instgram.
        /// </summary>
        public static string Instgram {
            get {
                return ResourceManager.GetString("Instgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Type.
        /// </summary>
        public static string JobType {
            get {
                return ResourceManager.GetString("JobType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Late.
        /// </summary>
        public static string Late {
            get {
                return ResourceManager.GetString("Late", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long.
        /// </summary>
        public static string Long {
            get {
                return ResourceManager.GetString("Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailbox.
        /// </summary>
        public static string Mailbox {
            get {
                return ResourceManager.GetString("Mailbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MailNo1.
        /// </summary>
        public static string MailNo1 {
            get {
                return ResourceManager.GetString("MailNo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MailNo2.
        /// </summary>
        public static string MailNo2 {
            get {
                return ResourceManager.GetString("MailNo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string ModalTitle {
            get {
                return ResourceManager.GetString("ModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhoneNo1.
        /// </summary>
        public static string PhoneNo1 {
            get {
                return ResourceManager.GetString("PhoneNo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhoneNo2.
        /// </summary>
        public static string PhoneNo2 {
            get {
                return ResourceManager.GetString("PhoneNo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostalCode.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirements.
        /// </summary>
        public static string Requirements {
            get {
                return ResourceManager.GetString("Requirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary Average.
        /// </summary>
        public static string SalaryAverage {
            get {
                return ResourceManager.GetString("SalaryAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Done Successfully.
        /// </summary>
        public static string SaveSuccessMessage {
            get {
                return ResourceManager.GetString("SaveSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapchat.
        /// </summary>
        public static string Snapchat {
            get {
                return ResourceManager.GetString("Snapchat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string TableBtnDelete {
            get {
                return ResourceManager.GetString("TableBtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string TableBtnEdit {
            get {
                return ResourceManager.GetString("TableBtnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string TitleDisplay {
            get {
                return ResourceManager.GetString("TitleDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter.
        /// </summary>
        public static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Pattern.
        /// </summary>
        public static string TxtaddressPatternErrorMessage {
            get {
                return ResourceManager.GetString("TxtaddressPatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to address is required.
        /// </summary>
        public static string TxtaddressRequiredErrorMessage {
            get {
                return ResourceManager.GetString("TxtaddressRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to address  is unique.
        /// </summary>
        public static string TxtaddressUniqueErrorMessage {
            get {
                return ResourceManager.GetString("TxtaddressUniqueErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description Invalid Pattern.
        /// </summary>
        public static string TxtDescPatternErrorMessage {
            get {
                return ResourceManager.GetString("TxtDescPatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descriptionis required.
        /// </summary>
        public static string TxtDescRequiredErrorMessage {
            get {
                return ResourceManager.GetString("TxtDescRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is unique.
        /// </summary>
        public static string TxtDescUniqueErrorMessage {
            get {
                return ResourceManager.GetString("TxtDescUniqueErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Pattern.
        /// </summary>
        public static string TxtFacebookPatternErrorMessage {
            get {
                return ResourceManager.GetString("TxtFacebookPatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook is required.
        /// </summary>
        public static string TxtFacebookRequiredErrorMessage {
            get {
                return ResourceManager.GetString("TxtFacebookRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Pattern.
        /// </summary>
        public static string TxtFaxPatternErrorMessage {
            get {
                return ResourceManager.GetString("TxtFaxPatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax is required.
        /// </summary>
        public static string TxtFaxRequiredErrorMessage {
            get {
                return ResourceManager.GetString("TxtFaxRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Invalid Pattern.
        /// </summary>
        public static string TxtImagePatternErrorMessage {
            get {
                return ResourceManager.GetString("TxtImagePatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image required.
        /// </summary>
        public static string TxtImageRequiredErrorMessage {
            get {
                return ResourceManager.GetString("TxtImageRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image is unique.
        /// </summary>
        public static string TxtImageUniqueErrorMessage {
            get {
                return ResourceManager.GetString("TxtImageUniqueErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Pattern.
        /// </summary>
        public static string TxtInstgramPatternErrorMessage {
            get {
                return ResourceManager.GetString("TxtInstgramPatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instgram is required.
        /// </summary>
        public static string TxtInstgramRequiredErrorMessage {
            get {
                return ResourceManager.GetString("TxtInstgramRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Pattern.
        /// </summary>
        public static string TxtLatePatternErrorMessage {
            get {
                return ResourceManager.GetString("TxtLatePatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Late is required.
        /// </summary>
        public static string TxtLateRequiredErrorMessage {
            get {
                return ResourceManager.GetString("TxtLateRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Pattern.
        /// </summary>
        public static string TxtLongPatternErrorMessage {
            get {
                return ResourceManager.GetString("TxtLongPatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long is required.
        /// </summary>
        public static string TxtLongRequiredErrorMessage {
            get {
                return ResourceManager.GetString("TxtLongRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Pattern.
        /// </summary>
        public static string TxtMailboxPatternErrorMessage {
            get {
                return ResourceManager.GetString("TxtMailboxPatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailbox is required.
        /// </summary>
        public static string TxtMailboxRequiredErrorMessage {
            get {
                return ResourceManager.GetString("TxtMailboxRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Mailbox is unique.
        /// </summary>
        public static string TxtMailboxUniqueErrorMessage {
            get {
                return ResourceManager.GetString("TxtMailboxUniqueErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Pattern.
        /// </summary>
        public static string TxtMailPatternErrorMessage {
            get {
                return ResourceManager.GetString("TxtMailPatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail is required.
        /// </summary>
        public static string TxtMailRequiredErrorMessage {
            get {
                return ResourceManager.GetString("TxtMailRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Mail is unique.
        /// </summary>
        public static string TxtMailUniqueErrorMessage {
            get {
                return ResourceManager.GetString("TxtMailUniqueErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Pattern.
        /// </summary>
        public static string TxtNamePatternErrorMessage {
            get {
                return ResourceManager.GetString("TxtNamePatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        public static string TxtNameRequiredErrorMessage {
            get {
                return ResourceManager.GetString("TxtNameRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name  is unique.
        /// </summary>
        public static string TxtNameUniqueErrorMessage {
            get {
                return ResourceManager.GetString("TxtNameUniqueErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Pattern.
        /// </summary>
        public static string TxtPhoneNo1PatternErrorMessage {
            get {
                return ResourceManager.GetString("TxtPhoneNo1PatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhoneNo1 is required.
        /// </summary>
        public static string TxtPhoneNo1RequiredErrorMessage {
            get {
                return ResourceManager.GetString("TxtPhoneNo1RequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  PhoneNo1 is unique.
        /// </summary>
        public static string TxtPhoneNo1UniqueErrorMessage {
            get {
                return ResourceManager.GetString("TxtPhoneNo1UniqueErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Pattern.
        /// </summary>
        public static string TxtPhoneNo2PatternErrorMessage {
            get {
                return ResourceManager.GetString("TxtPhoneNo2PatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhoneNo2 is required.
        /// </summary>
        public static string TxtPhoneNo2RequiredErrorMessage {
            get {
                return ResourceManager.GetString("TxtPhoneNo2RequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  PhoneNo2 is unique.
        /// </summary>
        public static string TxtPhoneNo2UniqueErrorMessage {
            get {
                return ResourceManager.GetString("TxtPhoneNo2UniqueErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Pattern.
        /// </summary>
        public static string TxtPostalcodePatternErrorMessage {
            get {
                return ResourceManager.GetString("TxtPostalcodePatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postalcode is required.
        /// </summary>
        public static string TxtPostalcodeRequiredErrorMessage {
            get {
                return ResourceManager.GetString("TxtPostalcodeRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search ....
        /// </summary>
        public static string txtSearchLbl {
            get {
                return ResourceManager.GetString("txtSearchLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Pattern.
        /// </summary>
        public static string TxtSnapchatPatternErrorMessage {
            get {
                return ResourceManager.GetString("TxtSnapchatPatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapchat is required.
        /// </summary>
        public static string TxtSnapchatRequiredErrorMessage {
            get {
                return ResourceManager.GetString("TxtSnapchatRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Pattern.
        /// </summary>
        public static string TxtTwitterPatternErrorMessage {
            get {
                return ResourceManager.GetString("TxtTwitterPatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter is required.
        /// </summary>
        public static string TxtTwitterRequiredErrorMessage {
            get {
                return ResourceManager.GetString("TxtTwitterRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Pattern.
        /// </summary>
        public static string TxtUrlPatternErrorMessage {
            get {
                return ResourceManager.GetString("TxtUrlPatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url is required.
        /// </summary>
        public static string TxtUrlRequiredErrorMessage {
            get {
                return ResourceManager.GetString("TxtUrlRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Pattern.
        /// </summary>
        public static string TxtWhatsAppPatternErrorMessage {
            get {
                return ResourceManager.GetString("TxtWhatsAppPatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WhatsApp is required.
        /// </summary>
        public static string TxtWhatsAppRequiredErrorMessage {
            get {
                return ResourceManager.GetString("TxtWhatsAppRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Pattern.
        /// </summary>
        public static string TxtYoutubePatternErrorMessage {
            get {
                return ResourceManager.GetString("TxtYoutubePatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youtube is required.
        /// </summary>
        public static string TxtYoutubeRequiredErrorMessage {
            get {
                return ResourceManager.GetString("TxtYoutubeRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Successfully.
        /// </summary>
        public static string UpdateSuccessMessage {
            get {
                return ResourceManager.GetString("UpdateSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacancies.
        /// </summary>
        public static string Vacancies {
            get {
                return ResourceManager.GetString("Vacancies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WhatsApp.
        /// </summary>
        public static string WhatsApp {
            get {
                return ResourceManager.GetString("WhatsApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youtube.
        /// </summary>
        public static string Youtube {
            get {
                return ResourceManager.GetString("Youtube", resourceCulture);
            }
        }
    }
}
