//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMG_Portal.Content.Admin.SystemParameters {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CustomerAccounts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CustomerAccounts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GMG_Portal.Content.Admin.SystemParameters.CustomerAccounts", typeof(CustomerAccounts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string BtnAdd {
            get {
                return ResourceManager.GetString("BtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string btnBack {
            get {
                return ResourceManager.GetString("btnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string btnSaveLbl {
            get {
                return ResourceManager.GetString("btnSaveLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t be deleted.
        /// </summary>
        public static string CannotDeleted {
            get {
                return ResourceManager.GetString("CannotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Successfully.
        /// </summary>
        public static string DeleteSuccessMessage {
            get {
                return ResourceManager.GetString("DeleteSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Status.
        /// </summary>
        public static string lblAccountStatus {
            get {
                return ResourceManager.GetString("lblAccountStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountType.
        /// </summary>
        public static string LblAccountType {
            get {
                return ResourceManager.GetString("LblAccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string lblAddress {
            get {
                return ResourceManager.GetString("lblAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name In Arabic.
        /// </summary>
        public static string lblArabicFirstName {
            get {
                return ResourceManager.GetString("lblArabicFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FamilyName In Arabic.
        /// </summary>
        public static string lblArabicLastName {
            get {
                return ResourceManager.GetString("lblArabicLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father Name In Arabic.
        /// </summary>
        public static string lblArabicSecondName {
            get {
                return ResourceManager.GetString("lblArabicSecondName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose City.
        /// </summary>
        public static string lblChooseCity {
            get {
                return ResourceManager.GetString("lblChooseCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Region.
        /// </summary>
        public static string lblChooseRegion {
            get {
                return ResourceManager.GetString("lblChooseRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string lblCity {
            get {
                return ResourceManager.GetString("lblCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Date.
        /// </summary>
        public static string lblContractDate {
            get {
                return ResourceManager.GetString("lblContractDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Number.
        /// </summary>
        public static string lblContractNumber {
            get {
                return ResourceManager.GetString("lblContractNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string lblCountry {
            get {
                return ResourceManager.GetString("lblCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wasel Email.
        /// </summary>
        public static string lblEmailWasel {
            get {
                return ResourceManager.GetString("lblEmailWasel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name In English.
        /// </summary>
        public static string lblEnglishFirstName {
            get {
                return ResourceManager.GetString("lblEnglishFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Name In English.
        /// </summary>
        public static string lblEnglishLastName {
            get {
                return ResourceManager.GetString("lblEnglishLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father Name In English.
        /// </summary>
        public static string lblEnglishSecondName {
            get {
                return ResourceManager.GetString("lblEnglishSecondName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string lblFax {
            get {
                return ResourceManager.GetString("lblFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instalments Number.
        /// </summary>
        public static string lblInstalmentsNumber {
            get {
                return ResourceManager.GetString("lblInstalmentsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Box.
        /// </summary>
        public static string lblMailBox {
            get {
                return ResourceManager.GetString("lblMailBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        public static string lblMobile {
            get {
                return ResourceManager.GetString("lblMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Type.
        /// </summary>
        public static string LblPaymentType {
            get {
                return ResourceManager.GetString("LblPaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person In Charge.
        /// </summary>
        public static string lblPersonInCharge {
            get {
                return ResourceManager.GetString("lblPersonInCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string lblPostalCode {
            get {
                return ResourceManager.GetString("lblPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string lblRegion {
            get {
                return ResourceManager.GetString("lblRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string lblTblName {
            get {
                return ResourceManager.GetString("lblTblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone Number.
        /// </summary>
        public static string lblTelephoneNumber {
            get {
                return ResourceManager.GetString("lblTelephoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Account Type .
        /// </summary>
        public static string LstAccountTypeRequiredErrorMessage {
            get {
                return ResourceManager.GetString("LstAccountTypeRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Account Type.
        /// </summary>
        public static string LstAccountTypesLbl {
            get {
                return ResourceManager.GetString("LstAccountTypesLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Country.
        /// </summary>
        public static string lstChooseCountry {
            get {
                return ResourceManager.GetString("lstChooseCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a city.
        /// </summary>
        public static string lstCityRequiredErrorMessage {
            get {
                return ResourceManager.GetString("lstCityRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a country.
        /// </summary>
        public static string lstCountryRequiredErrorMessage {
            get {
                return ResourceManager.GetString("lstCountryRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Payment Type.
        /// </summary>
        public static string LstPaymentTypeChooseLbl {
            get {
                return ResourceManager.GetString("LstPaymentTypeChooseLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a payment type.
        /// </summary>
        public static string LstPaymentTypeRequiredErrorMessage {
            get {
                return ResourceManager.GetString("LstPaymentTypeRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Region.
        /// </summary>
        public static string lstRegionRequiredErrorMessage {
            get {
                return ResourceManager.GetString("lstRegionRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Done Successfully.
        /// </summary>
        public static string SaveSuccessMessage {
            get {
                return ResourceManager.GetString("SaveSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Information.
        /// </summary>
        public static string TabBasicInformationTitle {
            get {
                return ResourceManager.GetString("TabBasicInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Data.
        /// </summary>
        public static string TabContractData {
            get {
                return ResourceManager.GetString("TabContractData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string TableBtnDelete {
            get {
                return ResourceManager.GetString("TableBtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string TableBtnEdit {
            get {
                return ResourceManager.GetString("TableBtnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Fieled Should Be Alphanumeric.
        /// </summary>
        public static string txtAddressPatternErrorMessage {
            get {
                return ResourceManager.GetString("txtAddressPatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter address details.
        /// </summary>
        public static string txtAddressRequiredErrorMessage {
            get {
                return ResourceManager.GetString("txtAddressRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Delivery Policy Fieled Should Be Alphanumeric.
        /// </summary>
        public static string TxtArabicDeliveryPolicyPatternErrorMessage {
            get {
                return ResourceManager.GetString("TxtArabicDeliveryPolicyPatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Pattern.
        /// </summary>
        public static string TxtArabicFirstNamePatternErrorMessage {
            get {
                return ResourceManager.GetString("TxtArabicFirstNamePatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the 1st Arabic name.
        /// </summary>
        public static string TxtArabicFirstNameRequiredErrorMessage {
            get {
                return ResourceManager.GetString("TxtArabicFirstNameRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Pattern.
        /// </summary>
        public static string TxtArabicLastNamePatternErrorMessage {
            get {
                return ResourceManager.GetString("TxtArabicLastNamePatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the Arabic family name.
        /// </summary>
        public static string TxtArabicLastNameRequiredErrorMessage {
            get {
                return ResourceManager.GetString("TxtArabicLastNameRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Pattern.
        /// </summary>
        public static string TxtArabicSecondNamePatternErrorMessage {
            get {
                return ResourceManager.GetString("TxtArabicSecondNamePatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the arabic father name.
        /// </summary>
        public static string TxtArabicSecondNameRequiredErrorMessage {
            get {
                return ResourceManager.GetString("TxtArabicSecondNameRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Shipment Policy Fieled Should Be Alphanumeric.
        /// </summary>
        public static string TxtArabicShipmentPolicyPatternErrorMessage {
            get {
                return ResourceManager.GetString("TxtArabicShipmentPolicyPatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Date format.
        /// </summary>
        public static string TxtContractDatePatternErrorMessage {
            get {
                return ResourceManager.GetString("TxtContractDatePatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the contract date.
        /// </summary>
        public static string TxtContractDateRequiredErrorMessage {
            get {
                return ResourceManager.GetString("TxtContractDateRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid contract number.
        /// </summary>
        public static string txtContractNumberPatternErrorMessage {
            get {
                return ResourceManager.GetString("txtContractNumberPatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the contract number.
        /// </summary>
        public static string txtContractNumberRequiredErrorMessage {
            get {
                return ResourceManager.GetString("txtContractNumberRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The e-mail format is incorrect.
        /// </summary>
        public static string txtEmailPatternErrorMessage {
            get {
                return ResourceManager.GetString("txtEmailPatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the e-mail account.
        /// </summary>
        public static string txtEmailRequiredErrorMessage {
            get {
                return ResourceManager.GetString("txtEmailRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Delivery Policy Fieled Should Be Alphanumeric.
        /// </summary>
        public static string TxtEnglishDeliveryPolicyPatternErrorMessage {
            get {
                return ResourceManager.GetString("TxtEnglishDeliveryPolicyPatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Pattern.
        /// </summary>
        public static string TxtEnglishFirstNamePatternErrorMessage {
            get {
                return ResourceManager.GetString("TxtEnglishFirstNamePatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the 1st English name.
        /// </summary>
        public static string TxtEnglishFirstNameRequiredErrorMessage {
            get {
                return ResourceManager.GetString("TxtEnglishFirstNameRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Pattern.
        /// </summary>
        public static string TxtEnglishLastNamePatternErrorMessage {
            get {
                return ResourceManager.GetString("TxtEnglishLastNamePatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the English family name.
        /// </summary>
        public static string TxtEnglishLastNameRequiredErrorMessage {
            get {
                return ResourceManager.GetString("TxtEnglishLastNameRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Pattern.
        /// </summary>
        public static string TxtEnglishSecondNamePatternErrorMessage {
            get {
                return ResourceManager.GetString("TxtEnglishSecondNamePatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the English father name.
        /// </summary>
        public static string TxtEnglishSecondNameRequiredErrorMessage {
            get {
                return ResourceManager.GetString("TxtEnglishSecondNameRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Shipment Policy Fieled Should Be Alphanumeric.
        /// </summary>
        public static string TxtEnglishShipmentPolicyPatternErrorMessage {
            get {
                return ResourceManager.GetString("TxtEnglishShipmentPolicyPatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Fax number  format is incorrect.
        /// </summary>
        public static string txtFaxPatternErrorMessage {
            get {
                return ResourceManager.GetString("txtFaxPatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of installments should be a Number greater than 0.
        /// </summary>
        public static string TxtInstalmentsNumberPatternErrorMessage {
            get {
                return ResourceManager.GetString("TxtInstalmentsNumberPatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the number of installments.
        /// </summary>
        public static string TxtInstalmentsNumberRequiredErrorMessage {
            get {
                return ResourceManager.GetString("TxtInstalmentsNumberRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Box Fieled Should Be number.
        /// </summary>
        public static string txtMailBoxPatternErrorMessage {
            get {
                return ResourceManager.GetString("txtMailBoxPatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mobile number  format is incorrect.
        /// </summary>
        public static string txtMobilePatternErrorMessage {
            get {
                return ResourceManager.GetString("txtMobilePatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the mobile number.
        /// </summary>
        public static string txtMobileRequiredErrorMessage {
            get {
                return ResourceManager.GetString("txtMobileRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Format.
        /// </summary>
        public static string TxtPersonInChargePatternErrorMessage {
            get {
                return ResourceManager.GetString("TxtPersonInChargePatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the person in charge.
        /// </summary>
        public static string TxtPersonInChargeRequiredErrorMessage {
            get {
                return ResourceManager.GetString("TxtPersonInChargeRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code  format is incorrect .
        /// </summary>
        public static string TxtPostalCodePatternErrorMessage {
            get {
                return ResourceManager.GetString("TxtPostalCodePatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search ....
        /// </summary>
        public static string txtSearchLbl {
            get {
                return ResourceManager.GetString("txtSearchLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Telephone Number Pattern.
        /// </summary>
        public static string txtTelephoneNumberPatternErrorMessage {
            get {
                return ResourceManager.GetString("txtTelephoneNumberPatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the telephone number.
        /// </summary>
        public static string txtTelephoneNumberRequiredErrorMessage {
            get {
                return ResourceManager.GetString("txtTelephoneNumberRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Successfully.
        /// </summary>
        public static string UpdateSuccessMessage {
            get {
                return ResourceManager.GetString("UpdateSuccessMessage", resourceCulture);
            }
        }
    }
}
