//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMG_Portal.Content.Admin.SystemParameters {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Languages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Languages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GMG_Portal.Content.Admin.SystemParameters.Languages", typeof(Languages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string BtnAdd {
            get {
                return ResourceManager.GetString("BtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string btnSaveLbl {
            get {
                return ResourceManager.GetString("btnSaveLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t be deleted.
        /// </summary>
        public static string CannotDeleted {
            get {
                return ResourceManager.GetString("CannotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Successfully.
        /// </summary>
        public static string DeleteSuccessMessage {
            get {
                return ResourceManager.GetString("DeleteSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Front.
        /// </summary>
        public static string DisplayFront {
            get {
                return ResourceManager.GetString("DisplayFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name must be unique.
        /// </summary>
        public static string EnglishNameUnique {
            get {
                return ResourceManager.GetString("EnglishNameUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        public static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string ModalTitle {
            get {
                return ResourceManager.GetString("ModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string NameDisplay {
            get {
                return ResourceManager.GetString("NameDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be unique.
        /// </summary>
        public static string NameUnique {
            get {
                return ResourceManager.GetString("NameUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Done Successfully.
        /// </summary>
        public static string SaveSuccessMessage {
            get {
                return ResourceManager.GetString("SaveSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string TableBtnDelete {
            get {
                return ResourceManager.GetString("TableBtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string TableBtnEdit {
            get {
                return ResourceManager.GetString("TableBtnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front Name is required.
        /// </summary>
        public static string TxtDisplayFrontRequiredErrorMessage {
            get {
                return ResourceManager.GetString("TxtDisplayFrontRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is unique.
        /// </summary>
        public static string TxtDisplayFrontUniqueErrorMessage {
            get {
                return ResourceManager.GetString("TxtDisplayFrontUniqueErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front Name.
        /// </summary>
        public static string TxtFrontNameLabel {
            get {
                return ResourceManager.GetString("TxtFrontNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front Name must be unique.
        /// </summary>
        public static string TxtFrontNameNotInList {
            get {
                return ResourceManager.GetString("TxtFrontNameNotInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Pattern.
        /// </summary>
        public static string TxtNameDisplayPatternErrorMessage {
            get {
                return ResourceManager.GetString("TxtNameDisplayPatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name is required.
        /// </summary>
        public static string TxtNameDisplayRequiredErrorMessage {
            get {
                return ResourceManager.GetString("TxtNameDisplayRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name is unique.
        /// </summary>
        public static string TxtNameDisplayUniqueErrorMessage {
            get {
                return ResourceManager.GetString("TxtNameDisplayUniqueErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front Name Invalid Pattern.
        /// </summary>
        public static string TxtNameFrontPatternErrorMessage {
            get {
                return ResourceManager.GetString("TxtNameFrontPatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string TxtNameLabel {
            get {
                return ResourceManager.GetString("TxtNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be unique.
        /// </summary>
        public static string TxtNameNotInList {
            get {
                return ResourceManager.GetString("TxtNameNotInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Pattern.
        /// </summary>
        public static string TxtNamePatternErrorMessage {
            get {
                return ResourceManager.GetString("TxtNamePatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        public static string TxtNameRequiredErrorMessage {
            get {
                return ResourceManager.GetString("TxtNameRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is unique.
        /// </summary>
        public static string TxtNameUniqueErrorMessage {
            get {
                return ResourceManager.GetString("TxtNameUniqueErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search ....
        /// </summary>
        public static string txtSearchLbl {
            get {
                return ResourceManager.GetString("txtSearchLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Successfully.
        /// </summary>
        public static string UpdateSuccessMessage {
            get {
                return ResourceManager.GetString("UpdateSuccessMessage", resourceCulture);
            }
        }
    }
}
