//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMG_Portal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class About_Translate
    {
        public int Id { get; set; }
        public string AboutTitle { get; set; }
        public string AboutDescription { get; set; }
        public string langId { get; set; }
        public Nullable<int> RecordId { get; set; }
        public string VisionTitle { get; set; }
        public string VisionDescription { get; set; }
        public string MissionTitle { get; set; }
        public string MissionDescription { get; set; }
        public string CoreValueTitle { get; set; }
        public string CoreValueDescription { get; set; }
    
        public virtual About About { get; set; }
    }
}
