//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMG_Portal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeView
    {
        public int Id { get; set; }
        public string DisplayValue { get; set; }
        public string DisplayValueDesc { get; set; }
        public bool IsDeleted { get; set; }
        public int News_Id { get; set; }
        public string News_DisplayValue { get; set; }
        public bool News_IsDeleted { get; set; }
        public string News_DisplayValueDesc { get; set; }
        public System.DateTime News_CreationTime { get; set; }
        public int HomeSlider_Id { get; set; }
        public string HomeSlider_DisplayValue { get; set; }
        public string HomeSlider_DisplayValueDesc { get; set; }
        public bool HomeSlider_IsDeleted { get; set; }
        public string HomeSlider_Image { get; set; }
        public string About_DisplayValue { get; set; }
        public string About_DisplayValueDesc { get; set; }
        public string About_Url { get; set; }
        public string Features_DisplayValue { get; set; }
        public bool Features_IsDeleted { get; set; }
        public string Features_DisplayValueDesc { get; set; }
        public string Features_Icon { get; set; }
        public string Images_Image { get; set; }
        public bool Images_IsDeleted { get; set; }
        public Nullable<int> Hotel_Id { get; set; }
    }
}
