//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMG_Portal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hotel()
        {
            this.Hotels_Features = new HashSet<Hotels_Features>();
            this.Hotels_Images = new HashSet<Hotels_Images>();
            this.Hotels_Reservation = new HashSet<Hotels_Reservation>();
            this.Hotels_Translate = new HashSet<Hotels_Translate>();
        }
    
        public int Id { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> Rate { get; set; }
        public string CheckIn { get; set; }
        public string CheckOut { get; set; }
        public Nullable<double> Late { get; set; }
        public Nullable<double> Long { get; set; }
        public string Email { get; set; }
        public Nullable<int> PriceStart { get; set; }
        public Nullable<double> DistanceDownTown { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<int> LastModifierUserId { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public Nullable<int> CreatorUserId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
        public Nullable<int> DeleterUserId { get; set; }
        public Nullable<int> Currency { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hotels_Features> Hotels_Features { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hotels_Images> Hotels_Images { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hotels_Reservation> Hotels_Reservation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hotels_Translate> Hotels_Translate { get; set; }
    }
}
