//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMG_Portal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotels_Reservation
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> CheckIn { get; set; }
        public Nullable<System.DateTime> CheckOut { get; set; }
        public Nullable<int> Adult { get; set; }
        public Nullable<int> Child { get; set; }
        public Nullable<int> HotelId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> SeenDate { get; set; }
        public Nullable<int> SeenBy { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public Nullable<int> OperationId { get; set; }
        public Nullable<bool> Seen { get; set; }
        public string HotelName { get; set; }
    }
}
