//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMG_Portal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotels_Features
    {
        public int Id { get; set; }
        public Nullable<int> Hotel_Id { get; set; }
        public Nullable<int> Feature_Id { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Feature Feature { get; set; }
        public virtual Hotel Hotel { get; set; }
    }
}
