//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMG_Portal.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GMG_Portal_DBEntities1 : DbContext
    {
        public GMG_Portal_DBEntities1()
            : base("name=GMG_Portal_DBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Front_Mission> Front_Mission { get; set; }
        public virtual DbSet<Front_Vision> Front_Vision { get; set; }
        public virtual DbSet<Hotel> Hotels { get; set; }
        public virtual DbSet<Hotels_Features> Hotels_Features { get; set; }
        public virtual DbSet<Hotels_Hotel_Features> Hotels_Hotel_Features { get; set; }
        public virtual DbSet<Hotels_Hotel_Payments> Hotels_Hotel_Payments { get; set; }
        public virtual DbSet<Hotels_Hotel_Phones> Hotels_Hotel_Phones { get; set; }
        public virtual DbSet<Hotels_Hotel_Videos> Hotels_Hotel_Videos { get; set; }
        public virtual DbSet<Hotles_Hotel_Offers> Hotles_Hotel_Offers { get; set; }
        public virtual DbSet<SystemParameter_Cities> SystemParameter_Cities { get; set; }
        public virtual DbSet<SystemParameter_Countries> SystemParameter_Countries { get; set; }
        public virtual DbSet<SystemParameter_Departments> SystemParameter_Departments { get; set; }
        public virtual DbSet<SystemParameter_PaymentType> SystemParameter_PaymentType { get; set; }
        public virtual DbSet<Hotels_Hotel_Images> Hotels_Hotel_Images { get; set; }
        public virtual DbSet<SystemParameters_LanguageText> SystemParameters_LanguageText { get; set; }
        public virtual DbSet<Systemparameters_Languages> Systemparameters_Languages { get; set; }
    }
}
