//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMG_Portal.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GMG_Portal_DBEntities1 : DbContext
    {
        public GMG_Portal_DBEntities1()
            : base("name=GMG_Portal_DBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<About> Abouts { get; set; }
        public virtual DbSet<About_Translate> About_Translate { get; set; }
        public virtual DbSet<Career> Careers { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Category_Translate> Category_Translate { get; set; }
        public virtual DbSet<ContactU> ContactUs { get; set; }
        public virtual DbSet<ContactUs_Translate> ContactUs_Translate { get; set; }
        public virtual DbSet<CoreValue> CoreValues { get; set; }
        public virtual DbSet<CoreValues_Translate> CoreValues_Translate { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<Currency_Translate> Currency_Translate { get; set; }
        public virtual DbSet<Feature> Features { get; set; }
        public virtual DbSet<Features_Translate> Features_Translate { get; set; }
        public virtual DbSet<HomeSlider> HomeSliders { get; set; }
        public virtual DbSet<HomeSlider_Translate> HomeSlider_Translate { get; set; }
        public virtual DbSet<Hotel> Hotels { get; set; }
        public virtual DbSet<Hotels_Features> Hotels_Features { get; set; }
        public virtual DbSet<Hotels_Features_Translate> Hotels_Features_Translate { get; set; }
        public virtual DbSet<Hotels_Images> Hotels_Images { get; set; }
        public virtual DbSet<Hotels_Images_Translate> Hotels_Images_Translate { get; set; }
        public virtual DbSet<Hotels_Payments> Hotels_Payments { get; set; }
        public virtual DbSet<Hotels_Phones> Hotels_Phones { get; set; }
        public virtual DbSet<Hotels_Videos> Hotels_Videos { get; set; }
        public virtual DbSet<Hotels_Reservation> Hotels_Reservation { get; set; }
        public virtual DbSet<Hotels_Translate> Hotels_Translate { get; set; }
        public virtual DbSet<Mission> Missions { get; set; }
        public virtual DbSet<Mission_Translate> Mission_Translate { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<News_Translate> News_Translate { get; set; }
        public virtual DbSet<Offer> Offers { get; set; }
        public virtual DbSet<Offers_Translate> Offers_Translate { get; set; }
        public virtual DbSet<Owner> Owners { get; set; }
        public virtual DbSet<Owners_Translate> Owners_Translate { get; set; }
        public virtual DbSet<Systemparameters_Admin> Systemparameters_Admin { get; set; }
        public virtual DbSet<SystemParameters_CareerForm> SystemParameters_CareerForm { get; set; }
        public virtual DbSet<SystemParameters_Cities> SystemParameters_Cities { get; set; }
        public virtual DbSet<SystemParameters_ContactForm> SystemParameters_ContactForm { get; set; }
        public virtual DbSet<SystemParameters_Countries> SystemParameters_Countries { get; set; }
        public virtual DbSet<SystemParameters_Departments> SystemParameters_Departments { get; set; }
        public virtual DbSet<Systemparameters_Languages> Systemparameters_Languages { get; set; }
        public virtual DbSet<SystemParameters_LanguageText> SystemParameters_LanguageText { get; set; }
        public virtual DbSet<SystemParameters_Newsletter> SystemParameters_Newsletter { get; set; }
        public virtual DbSet<SystemParameters_Notify> SystemParameters_Notify { get; set; }
        public virtual DbSet<SystemParameters_NotifyDepartment> SystemParameters_NotifyDepartment { get; set; }
        public virtual DbSet<SystemParameters_PaymentType> SystemParameters_PaymentType { get; set; }
        public virtual DbSet<Vision> Visions { get; set; }
        public virtual DbSet<Vision_Translate> Vision_Translate { get; set; }
    }
}
