//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMG_Portal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemParameters_Careers_Translate
    {
        public int Id { get; set; }
        public Nullable<System.Guid> SGuid { get; set; }
        public string DisplayValue { get; set; }
        public Nullable<int> LookupKey { get; set; }
        public Nullable<System.Guid> LookupKeyGuid { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> Show { get; set; }
        public string DisplayValueDesc { get; set; }
        public Nullable<int> LookupKeyDesc { get; set; }
        public Nullable<System.Guid> LookupKeyGuidDesc { get; set; }
        public string Image { get; set; }
        public string SalaryAverage { get; set; }
        public string Experience { get; set; }
        public string CareerLevel { get; set; }
        public string JobType { get; set; }
        public string EducationLevel { get; set; }
        public Nullable<int> Vacancies { get; set; }
        public string DisplayValueRequirements { get; set; }
        public Nullable<int> LookupKeyRequirements { get; set; }
        public Nullable<System.Guid> LookupKeyGuidRequirements { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<int> LastModifierUserId { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public Nullable<int> CreatorUserId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
        public Nullable<int> DeleterUserId { get; set; }
        public string Lang_ID { get; set; }
    }
}
