//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMG_Portal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemParameters_ContactUs
    {
        public int Id { get; set; }
        public Nullable<System.Guid> SGuid { get; set; }
        public string DisplayValueAddress { get; set; }
        public Nullable<int> LookupKeyAddress { get; set; }
        public Nullable<System.Guid> LookupKeyGuidAddress { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> Show { get; set; }
        public string DisplayValueDesc { get; set; }
        public Nullable<int> LookupKeyDesc { get; set; }
        public Nullable<System.Guid> LookupKeyGuidDesc { get; set; }
        public string Image { get; set; }
        public string Url { get; set; }
        public string Facebook { get; set; }
        public string Twitter { get; set; }
        public string Instgram { get; set; }
        public string Youtube { get; set; }
        public string Snapchat { get; set; }
        public string Fax { get; set; }
        public string WhatsApp { get; set; }
        public string PhoneNo1 { get; set; }
        public string PhoneNo2 { get; set; }
        public string PostalCode { get; set; }
        public string Mailbox { get; set; }
        public Nullable<double> Late { get; set; }
        public Nullable<double> Long { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<int> LastModifierUserId { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public Nullable<int> CreatorUserId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
        public Nullable<int> DeleterUserId { get; set; }
    }
}
