//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMG_Portal.Content.Admin.Hotel {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Reservation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Reservation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GMG_Portal.Content.Admin.Hotel.Reservation", typeof(Reservation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adult.
        /// </summary>
        public static string Adult {
            get {
                return ResourceManager.GetString("Adult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Count.
        /// </summary>
        public static string ApplyCount {
            get {
                return ResourceManager.GetString("ApplyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string BtnAdd {
            get {
                return ResourceManager.GetString("BtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string btnSaveLbl {
            get {
                return ResourceManager.GetString("btnSaveLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t be deleted.
        /// </summary>
        public static string CannotDeleted {
            get {
                return ResourceManager.GetString("CannotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Career Level.
        /// </summary>
        public static string CareerLevel {
            get {
                return ResourceManager.GetString("CareerLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckIn.
        /// </summary>
        public static string CheckIn {
            get {
                return ResourceManager.GetString("CheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckOut.
        /// </summary>
        public static string CheckOut {
            get {
                return ResourceManager.GetString("CheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child.
        /// </summary>
        public static string Child {
            get {
                return ResourceManager.GetString("Child", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreationTime.
        /// </summary>
        public static string CreationTime {
            get {
                return ResourceManager.GetString("CreationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Successfully.
        /// </summary>
        public static string DeleteSuccessMessage {
            get {
                return ResourceManager.GetString("DeleteSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Desc {
            get {
                return ResourceManager.GetString("Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DescDisplay {
            get {
                return ResourceManager.GetString("DescDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Front.
        /// </summary>
        public static string DisplayFront {
            get {
                return ResourceManager.GetString("DisplayFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string DisplayValueAddress {
            get {
                return ResourceManager.GetString("DisplayValueAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education Level.
        /// </summary>
        public static string EducationLevel {
            get {
                return ResourceManager.GetString("EducationLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name must be unique.
        /// </summary>
        public static string EnglishNameUnique {
            get {
                return ResourceManager.GetString("EnglishNameUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience.
        /// </summary>
        public static string Experience {
            get {
                return ResourceManager.GetString("Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstName.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HotelId.
        /// </summary>
        public static string HotelId {
            get {
                return ResourceManager.GetString("HotelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HotelName.
        /// </summary>
        public static string HotelName {
            get {
                return ResourceManager.GetString("HotelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        public static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Type.
        /// </summary>
        public static string JobType {
            get {
                return ResourceManager.GetString("JobType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation.
        /// </summary>
        public static string ModalTitle {
            get {
                return ResourceManager.GetString("ModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Res. Number #.
        /// </summary>
        public static string OperationId {
            get {
                return ResourceManager.GetString("OperationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postion.
        /// </summary>
        public static string Postion {
            get {
                return ResourceManager.GetString("Postion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirements.
        /// </summary>
        public static string Requirements {
            get {
                return ResourceManager.GetString("Requirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary Average.
        /// </summary>
        public static string SalaryAverage {
            get {
                return ResourceManager.GetString("SalaryAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Done Successfully.
        /// </summary>
        public static string SaveSuccessMessage {
            get {
                return ResourceManager.GetString("SaveSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seen.
        /// </summary>
        public static string Seen {
            get {
                return ResourceManager.GetString("Seen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string TableBtnDelete {
            get {
                return ResourceManager.GetString("TableBtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string TableBtnEdit {
            get {
                return ResourceManager.GetString("TableBtnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string TitleDisplay {
            get {
                return ResourceManager.GetString("TitleDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description Invalid Pattern.
        /// </summary>
        public static string TxtDescPatternErrorMessage {
            get {
                return ResourceManager.GetString("TxtDescPatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descriptionis required.
        /// </summary>
        public static string TxtDescRequiredErrorMessage {
            get {
                return ResourceManager.GetString("TxtDescRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is unique.
        /// </summary>
        public static string TxtDescUniqueErrorMessage {
            get {
                return ResourceManager.GetString("TxtDescUniqueErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Invalid Pattern.
        /// </summary>
        public static string TxtImagePatternErrorMessage {
            get {
                return ResourceManager.GetString("TxtImagePatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image required.
        /// </summary>
        public static string TxtImageRequiredErrorMessage {
            get {
                return ResourceManager.GetString("TxtImageRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image is unique.
        /// </summary>
        public static string TxtImageUniqueErrorMessage {
            get {
                return ResourceManager.GetString("TxtImageUniqueErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Pattern.
        /// </summary>
        public static string TxtNamePatternErrorMessage {
            get {
                return ResourceManager.GetString("TxtNamePatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        public static string TxtNameRequiredErrorMessage {
            get {
                return ResourceManager.GetString("TxtNameRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name  is unique.
        /// </summary>
        public static string TxtNameUniqueErrorMessage {
            get {
                return ResourceManager.GetString("TxtNameUniqueErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Pattern.
        /// </summary>
        public static string TxtPostionPatternErrorMessage {
            get {
                return ResourceManager.GetString("TxtPostionPatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postion is required.
        /// </summary>
        public static string TxtPostionRequiredErrorMessage {
            get {
                return ResourceManager.GetString("TxtPostionRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postion  is unique.
        /// </summary>
        public static string TxtPostionUniqueErrorMessage {
            get {
                return ResourceManager.GetString("TxtPostionUniqueErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search ....
        /// </summary>
        public static string txtSearchLbl {
            get {
                return ResourceManager.GetString("txtSearchLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url Invalid Pattern.
        /// </summary>
        public static string TxtUrlPatternErrorMessage {
            get {
                return ResourceManager.GetString("TxtUrlPatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Successfully.
        /// </summary>
        public static string UpdateSuccessMessage {
            get {
                return ResourceManager.GetString("UpdateSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacancies.
        /// </summary>
        public static string Vacancies {
            get {
                return ResourceManager.GetString("Vacancies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
    }
}
