//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Front.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Front.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach file Required.
        /// </summary>
        public static string Attach_file_Required {
            get {
                return ResourceManager.GetString("Attach_file_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Required.
        /// </summary>
        public static string Email_Required {
            get {
                return ResourceManager.GetString("Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name Required.
        /// </summary>
        public static string First_Name_Required {
            get {
                return ResourceManager.GetString("First_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string Footer_ContactUs {
            get {
                return ResourceManager.GetString("Footer_ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2017 GMG Technology Group . All rights reserved..
        /// </summary>
        public static string Footer_CopyRights {
            get {
                return ResourceManager.GetString("Footer_CopyRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewsLetter.
        /// </summary>
        public static string Footer_Newsletter {
            get {
                return ResourceManager.GetString("Footer_Newsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Email.
        /// </summary>
        public static string Footer_NewsletterBoxEmail {
            get {
                return ResourceManager.GetString("Footer_NewsletterBoxEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe.
        /// </summary>
        public static string Footer_NewsletterButton {
            get {
                return ResourceManager.GetString("Footer_NewsletterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe to Our Newsletter.
        /// </summary>
        public static string Footer_NewsletterDesc {
            get {
                return ResourceManager.GetString("Footer_NewsletterDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Submitted , Thank you !.
        /// </summary>
        public static string Footer_NewsletterSubmitMsg {
            get {
                return ResourceManager.GetString("Footer_NewsletterSubmitMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Media.
        /// </summary>
        public static string Footer_SocialMedia {
            get {
                return ResourceManager.GetString("Footer_SocialMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter.
        /// </summary>
        public static string Footer_Twitter {
            get {
                return ResourceManager.GetString("Footer_Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Header_About {
            get {
                return ResourceManager.GetString("Header_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Careers.
        /// </summary>
        public static string Header_Careers {
            get {
                return ResourceManager.GetString("Header_Careers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Header_Contact {
            get {
                return ResourceManager.GetString("Header_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Header_Home {
            get {
                return ResourceManager.GetString("Header_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotels.
        /// </summary>
        public static string Header_Hotels {
            get {
                return ResourceManager.GetString("Header_Hotels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string Header_Languages {
            get {
                return ResourceManager.GetString("Header_Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string Header_News {
            get {
                return ResourceManager.GetString("Header_News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offers.
        /// </summary>
        public static string Header_Offers {
            get {
                return ResourceManager.GetString("Header_Offers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owners.
        /// </summary>
        public static string Header_Owners {
            get {
                return ResourceManager.GetString("Header_Owners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These best rooms chosen by our customers.
        /// </summary>
        public static string Home_HotelFacilitiesDesc {
            get {
                return ResourceManager.GetString("Home_HotelFacilitiesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOTEL FACILTIES.
        /// </summary>
        public static string Home_HotelFacilitiesTitle {
            get {
                return ResourceManager.GetString("Home_HotelFacilitiesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUR GALLERY.
        /// </summary>
        public static string Home_OurGallery {
            get {
                return ResourceManager.GetString("Home_OurGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These best rooms chosen by our customers.
        /// </summary>
        public static string Home_OurHotelsDesc {
            get {
                return ResourceManager.GetString("Home_OurHotelsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUR BEST ROOMS.
        /// </summary>
        public static string Home_OurHotelsTitle {
            get {
                return ResourceManager.GetString("Home_OurHotelsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are the Visionary Minds Behind our Success.
        /// </summary>
        public static string Home_OwnersDesc {
            get {
                return ResourceManager.GetString("Home_OwnersDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEADERSHIP.
        /// </summary>
        public static string Home_OwnersTitle {
            get {
                return ResourceManager.GetString("Home_OwnersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECENT NEWS.
        /// </summary>
        public static string Home_RecentNews {
            get {
                return ResourceManager.GetString("Home_RecentNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adult.
        /// </summary>
        public static string Home_SearchRoomsAdult {
            get {
                return ResourceManager.GetString("Home_SearchRoomsAdult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Now.
        /// </summary>
        public static string Home_SearchRoomsButton {
            get {
                return ResourceManager.GetString("Home_SearchRoomsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check In.
        /// </summary>
        public static string Home_SearchRoomsCheckin {
            get {
                return ResourceManager.GetString("Home_SearchRoomsCheckin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Out.
        /// </summary>
        public static string Home_SearchRoomsCheckout {
            get {
                return ResourceManager.GetString("Home_SearchRoomsCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child.
        /// </summary>
        public static string Home_SearchRoomsChild {
            get {
                return ResourceManager.GetString("Home_SearchRoomsChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOR RATES &amp; AVAILABILITY.
        /// </summary>
        public static string Home_SearchRoomsDesc {
            get {
                return ResourceManager.GetString("Home_SearchRoomsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEARCH ROOMS.
        /// </summary>
        public static string Home_SearchRoomsTitle {
            get {
                return ResourceManager.GetString("Home_SearchRoomsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name Required.
        /// </summary>
        public static string Last_Name_Required {
            get {
                return ResourceManager.GetString("Last_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhoneNo Required.
        /// </summary>
        public static string PhoneNo_Required {
            get {
                return ResourceManager.GetString("PhoneNo_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See More.
        /// </summary>
        public static string SeeMore {
            get {
                return ResourceManager.GetString("SeeMore", resourceCulture);
            }
        }
    }
}
