//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMG_Portal.Content.Admin.Customer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MaintenanceContracts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MaintenanceContracts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CRM.Content.Admin.Customer.MaintenanceContracts", typeof(MaintenanceContracts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic name must be unique.
        /// </summary>
        public static string ArabicNameUnique {
            get {
                return ResourceManager.GetString("ArabicNameUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string BtnAdd {
            get {
                return ResourceManager.GetString("BtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string btnSaveLbl {
            get {
                return ResourceManager.GetString("btnSaveLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t be deleted.
        /// </summary>
        public static string CannotDeleted {
            get {
                return ResourceManager.GetString("CannotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Date.
        /// </summary>
        public static string ContractDate {
            get {
                return ResourceManager.GetString("ContractDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract End Date.
        /// </summary>
        public static string ContractEndDate {
            get {
                return ResourceManager.GetString("ContractEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Contract Already Exist.
        /// </summary>
        public static string CustomerContractAlreadyExist {
            get {
                return ResourceManager.GetString("CustomerContractAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Successfully.
        /// </summary>
        public static string DeleteSuccessMessage {
            get {
                return ResourceManager.GetString("DeleteSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English name must be unique.
        /// </summary>
        public static string EnglishNameUnique {
            get {
                return ResourceManager.GetString("EnglishNameUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstInvoice Due Date.
        /// </summary>
        public static string FirstInvoiceDueDate {
            get {
                return ResourceManager.GetString("FirstInvoiceDueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Frequency is required.
        /// </summary>
        public static string LstMaintenanceFrequencyErrorMessage {
            get {
                return ResourceManager.GetString("LstMaintenanceFrequencyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Frequency is required.
        /// </summary>
        public static string LstPaymentFrequencyErrorMessage {
            get {
                return ResourceManager.GetString("LstPaymentFrequencyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Frequency.
        /// </summary>
        public static string MaintenanceFrequency {
            get {
                return ResourceManager.GetString("MaintenanceFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Contract.
        /// </summary>
        public static string ModalTitle {
            get {
                return ResourceManager.GetString("ModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Name.
        /// </summary>
        public static string NameAr {
            get {
                return ResourceManager.GetString("NameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Name.
        /// </summary>
        public static string NameEn {
            get {
                return ResourceManager.GetString("NameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Frequency.
        /// </summary>
        public static string PaymentFrequency {
            get {
                return ResourceManager.GetString("PaymentFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Done Successfully.
        /// </summary>
        public static string SaveSuccessMessage {
            get {
                return ResourceManager.GetString("SaveSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string TableBtnDelete {
            get {
                return ResourceManager.GetString("TableBtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string TableBtnEdit {
            get {
                return ResourceManager.GetString("TableBtnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Name.
        /// </summary>
        public static string TxtNameArLabel {
            get {
                return ResourceManager.GetString("TxtNameArLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be unique.
        /// </summary>
        public static string TxtNameArNotInList {
            get {
                return ResourceManager.GetString("TxtNameArNotInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Pattern.
        /// </summary>
        public static string TxtNameArPatternErrorMessage {
            get {
                return ResourceManager.GetString("TxtNameArPatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic name is required.
        /// </summary>
        public static string TxtNameArRequiredErrorMessage {
            get {
                return ResourceManager.GetString("TxtNameArRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Name is unique.
        /// </summary>
        public static string TxtNameArUniqueErrorMessage {
            get {
                return ResourceManager.GetString("TxtNameArUniqueErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Pattern.
        /// </summary>
        public static string TxtNameEnPatternErrorMessage {
            get {
                return ResourceManager.GetString("TxtNameEnPatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English name is required.
        /// </summary>
        public static string TxtNameEnRequiredErrorMessage {
            get {
                return ResourceManager.GetString("TxtNameEnRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Name is unique.
        /// </summary>
        public static string TxtNameEnUniqueErrorMessage {
            get {
                return ResourceManager.GetString("TxtNameEnUniqueErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search ....
        /// </summary>
        public static string txtSearchLbl {
            get {
                return ResourceManager.GetString("txtSearchLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Successfully.
        /// </summary>
        public static string UpdateSuccessMessage {
            get {
                return ResourceManager.GetString("UpdateSuccessMessage", resourceCulture);
            }
        }
         
        public static string LstCustomerErrorMessage
        {
            get
            {
                return ResourceManager.GetString("LstCustomerErrorMessage", resourceCulture);
            }
        }
        public static string TxtContractDateRequiredErrorMessage
        {
            get
            {
                return ResourceManager.GetString("TxtContractDateRequiredErrorMessage", resourceCulture);
            }
        }
        public static string TxtContractDatePatternErrorMessage
        {
            get
            {
                return ResourceManager.GetString("TxtContractDatePatternErrorMessage", resourceCulture);
            }
        }
        public static string AmountUniqueErrorMessage
        {
            get
            {
                return ResourceManager.GetString("AmountUniqueErrorMessage", resourceCulture);
            }
        }
        public static string AmountPatternErrorMessage
        {
            get
            {
                return ResourceManager.GetString("AmountPatternErrorMessage", resourceCulture);
            }
        }
        public static string AmountRequiredErrorMessage
        {
            get
            {
                return ResourceManager.GetString("AmountRequiredErrorMessage", resourceCulture);
            }
        } 
    }
}
