//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMG_Portal.Content.Admin.Inventory {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Products {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Products() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GMG_Portal.Content.Admin.Inventory.Products", typeof(Products).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Key Features.
        /// </summary>
        public static string ArabicKeyFeaturesLbl {
            get {
                return ResourceManager.GetString("ArabicKeyFeaturesLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic name must be unique.
        /// </summary>
        public static string ArabicNameUnique {
            get {
                return ResourceManager.GetString("ArabicNameUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Product Description.
        /// </summary>
        public static string ArabicProductDescriptionLbl {
            get {
                return ResourceManager.GetString("ArabicProductDescriptionLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string BtnAdd {
            get {
                return ResourceManager.GetString("BtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string btnSaveLbl {
            get {
                return ResourceManager.GetString("btnSaveLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t be deleted.
        /// </summary>
        public static string CannotDeleted {
            get {
                return ResourceManager.GetString("CannotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Successfully.
        /// </summary>
        public static string DeleteSuccessMessage {
            get {
                return ResourceManager.GetString("DeleteSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Percentage.
        /// </summary>
        public static string DiscountPercentageLbl {
            get {
                return ResourceManager.GetString("DiscountPercentageLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Key Features.
        /// </summary>
        public static string EnglishKeyFeaturesLbl {
            get {
                return ResourceManager.GetString("EnglishKeyFeaturesLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English name must be unique.
        /// </summary>
        public static string EnglishNameUnique {
            get {
                return ResourceManager.GetString("EnglishNameUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Product Description.
        /// </summary>
        public static string EnglishProductDescriptionLbl {
            get {
                return ResourceManager.GetString("EnglishProductDescriptionLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related with products.
        /// </summary>
        public static string HasChildreen {
            get {
                return ResourceManager.GetString("HasChildreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string LblBrand {
            get {
                return ResourceManager.GetString("LblBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Category.
        /// </summary>
        public static string LblProductCategory {
            get {
                return ResourceManager.GetString("LblProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Brand.
        /// </summary>
        public static string LstBrandChooseLbl {
            get {
                return ResourceManager.GetString("LstBrandChooseLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a brand.
        /// </summary>
        public static string LstBrandRequiredErrorMessage {
            get {
                return ResourceManager.GetString("LstBrandRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Product Category.
        /// </summary>
        public static string LstProductCategoryChooseLbl {
            get {
                return ResourceManager.GetString("LstProductCategoryChooseLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a category.
        /// </summary>
        public static string LstProductCategoryRequiredErrorMessage {
            get {
                return ResourceManager.GetString("LstProductCategoryRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Product Size.
        /// </summary>
        public static string LstProductSizeChooseLbl {
            get {
                return ResourceManager.GetString("LstProductSizeChooseLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select product type.
        /// </summary>
        public static string LstProductSizeRequiredErrorMessage {
            get {
                return ResourceManager.GetString("LstProductSizeRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string ModalTitle {
            get {
                return ResourceManager.GetString("ModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Arabic Name.
        /// </summary>
        public static string NameAr {
            get {
                return ResourceManager.GetString("NameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product EnglishName.
        /// </summary>
        public static string NameEn {
            get {
                return ResourceManager.GetString("NameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Units.
        /// </summary>
        public static string NumberOfUnitsLbl {
            get {
                return ResourceManager.GetString("NumberOfUnitsLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Arabic Name.
        /// </summary>
        public static string ProductArabicNameLbl {
            get {
                return ResourceManager.GetString("ProductArabicNameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product English Name.
        /// </summary>
        public static string ProductEnglishNameLbl {
            get {
                return ResourceManager.GetString("ProductEnglishNameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Size.
        /// </summary>
        public static string ProductSizeLbl {
            get {
                return ResourceManager.GetString("ProductSizeLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Done Successfully.
        /// </summary>
        public static string SaveSuccessMessage {
            get {
                return ResourceManager.GetString("SaveSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Information.
        /// </summary>
        public static string TabBasicInformationTitle {
            get {
                return ResourceManager.GetString("TabBasicInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string TabDescriptionTitle {
            get {
                return ResourceManager.GetString("TabDescriptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string TableBtnDelete {
            get {
                return ResourceManager.GetString("TableBtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string TableBtnEdit {
            get {
                return ResourceManager.GetString("TableBtnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Rate.
        /// </summary>
        public static string TaxRateLbl {
            get {
                return ResourceManager.GetString("TaxRateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Key Feature Fieled Should Be Alphanumeric.
        /// </summary>
        public static string TxtArabicKeyFeaturePatternErrorMessage {
            get {
                return ResourceManager.GetString("TxtArabicKeyFeaturePatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Product Description Fieled Should Be Alphanumeric.
        /// </summary>
        public static string TxtArabicProductDescriptionPatternErrorMessage {
            get {
                return ResourceManager.GetString("TxtArabicProductDescriptionPatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax percentage shouldn’t be less than 0.
        /// </summary>
        public static string TxtDiscountPercentagePatternErrorMessage {
            get {
                return ResourceManager.GetString("TxtDiscountPercentagePatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter tax percentage.
        /// </summary>
        public static string TxtDiscountPercentageRequiredErrorMessage {
            get {
                return ResourceManager.GetString("TxtDiscountPercentageRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Key Features Fieled Should Be Alphanumeric.
        /// </summary>
        public static string TxtEnglishKeyFeaturesPatternErrorMessage {
            get {
                return ResourceManager.GetString("TxtEnglishKeyFeaturesPatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Product Description Fieled Should Be Alphanumeric.
        /// </summary>
        public static string TxtEnglishProductDescriptionPatternErrorMessage {
            get {
                return ResourceManager.GetString("TxtEnglishProductDescriptionPatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be unique.
        /// </summary>
        public static string TxtNameArNotInList {
            get {
                return ResourceManager.GetString("TxtNameArNotInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Pattern.
        /// </summary>
        public static string TxtNameArPatternErrorMessage {
            get {
                return ResourceManager.GetString("TxtNameArPatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic name is required.
        /// </summary>
        public static string TxtNameArRequiredErrorMessage {
            get {
                return ResourceManager.GetString("TxtNameArRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Name is unique.
        /// </summary>
        public static string TxtNameArUniqueErrorMessage {
            get {
                return ResourceManager.GetString("TxtNameArUniqueErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Pattern.
        /// </summary>
        public static string TxtNameEnPatternErrorMessage {
            get {
                return ResourceManager.GetString("TxtNameEnPatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English name is required.
        /// </summary>
        public static string TxtNameEnRequiredErrorMessage {
            get {
                return ResourceManager.GetString("TxtNameEnRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Name is unique.
        /// </summary>
        public static string TxtNameEnUniqueErrorMessage {
            get {
                return ResourceManager.GetString("TxtNameEnUniqueErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number  of units shouldn’t be less than 0.
        /// </summary>
        public static string TxtNumberOfUnitsPatternErrorMessage {
            get {
                return ResourceManager.GetString("TxtNumberOfUnitsPatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Units Fieled Is Required.
        /// </summary>
        public static string TxtNumberOfUnitsRequiredErrorMessage {
            get {
                return ResourceManager.GetString("TxtNumberOfUnitsRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search ....
        /// </summary>
        public static string txtSearchLbl {
            get {
                return ResourceManager.GetString("txtSearchLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Rate Fieled Should Be Number Greater Than Or Equal To Zero.
        /// </summary>
        public static string TxtTaxRatePatternErrorMessage {
            get {
                return ResourceManager.GetString("TxtTaxRatePatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Rate Fieled  Is  Required.
        /// </summary>
        public static string TxtTaxRateRequiredErrorMessage {
            get {
                return ResourceManager.GetString("TxtTaxRateRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price Fieled Must Be Number Greater Than Zero.
        /// </summary>
        public static string TxtTxtUnitPricePatternErrorMessage {
            get {
                return ResourceManager.GetString("TxtTxtUnitPricePatternErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price Fieled is Required.
        /// </summary>
        public static string TxtTxtUnitPriceRequiredErrorMessage {
            get {
                return ResourceManager.GetString("TxtTxtUnitPriceRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        public static string UnitPriceLbl {
            get {
                return ResourceManager.GetString("UnitPriceLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Successfully.
        /// </summary>
        public static string UpdateSuccessMessage {
            get {
                return ResourceManager.GetString("UpdateSuccessMessage", resourceCulture);
            }
        }
    }
}
