//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMG_Portal.Content {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GMG_Portal.Content.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charachter.
        /// </summary>
        public static string Charachter {
            get {
                return ResourceManager.GetString("Charachter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 120.
        /// </summary>
        public static string DescMax120 {
            get {
                return ResourceManager.GetString("DescMax120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200.
        /// </summary>
        public static string DescMax200 {
            get {
                return ResourceManager.GetString("DescMax200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7000.
        /// </summary>
        public static string DescMax7000 {
            get {
                return ResourceManager.GetString("DescMax7000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 800.
        /// </summary>
        public static string DescMax800 {
            get {
                return ResourceManager.GetString("DescMax800", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 81.
        /// </summary>
        public static string DescMax81 {
            get {
                return ResourceManager.GetString("DescMax81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        public static string DescMin30 {
            get {
                return ResourceManager.GetString("DescMin30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50.
        /// </summary>
        public static string DescMin50 {
            get {
                return ResourceManager.GetString("DescMin50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digits.
        /// </summary>
        public static string Digtis {
            get {
                return ResourceManager.GetString("Digtis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum.
        /// </summary>
        public static string MaximumKeyWord {
            get {
                return ResourceManager.GetString("MaximumKeyWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum.
        /// </summary>
        public static string MinimumKeyWord {
            get {
                return ResourceManager.GetString("MinimumKeyWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25.
        /// </summary>
        public static string TitleMax25 {
            get {
                return ResourceManager.GetString("TitleMax25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        public static string TitleMax5 {
            get {
                return ResourceManager.GetString("TitleMax5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 65.
        /// </summary>
        public static string TitleMax65 {
            get {
                return ResourceManager.GetString("TitleMax65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25.
        /// </summary>
        public static string TitleMin25 {
            get {
                return ResourceManager.GetString("TitleMin25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        public static string TitleMin30 {
            get {
                return ResourceManager.GetString("TitleMin30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        public static string TitleMin5 {
            get {
                return ResourceManager.GetString("TitleMin5", resourceCulture);
            }
        }
    }
}
